### ISSUE TITLE
Problem with integers

### ISSUE THREAD

**Issue by avatec** [stationer/SortTable#1]
Doesn't sort by numbers correctly ex:

1,2,20,21,3,4....

**Comment by tyleruebele** [comment]
The script does not do detection of types, but accepts hints in the form of classes applied to the table headers. See https://github.com/tyleruebele/sort-table/blob/43a65da6cd5061551cd1c1d1710beefbafc2cad3/demo.html#L49 for an example of sorting by number.  What this does is hint the script to convert each value to a `Number` before comparing, which resolves the correct sort order.  See https://github.com/tyleruebele/sort-table/blob/43a65da6cd5061551cd1c1d1710beefbafc2cad3/sort-table.js#L135-L137 for that part of the script and notice a few other supported types thereabout.
