### ISSUE TITLE
Dealing with scientific notations?

### ISSUE THREAD

**Issue by xjtu-blacksmith** [stationer/SortTable#11]
Hello! I've tried your sorting code and it works very well for numbers in most case, after adding the class `js-sort-number` for table headers. However, in my page sometimes the numbers are in scientific notations, like `3.11e-5`, which current codes do not handle well.

I've checked the source code, and I think the problem arises when stripping the "irrelevant" characters by regex `/[^-\d.]/g` in function `sortTable.number`, where `e` or `E` in scientific notations are removed and therefore cause some trouble. Currently I make a workaround by not replacing these characters in regex replacement, but it does not seem to be a general solution when the cases become more complex (where you still have to remove `e` or `E` because the value is actually not a scientific notation).

Maybe the best way is to check the value first; if it is scientific notation, no replacement should be carried out, otherwise applying current replacement process.

**Comment by tyleruebele** [comment]
Hello!
I wrote a regex to test various valid number formats.  It's not exhaustive, but it might get you where you need to get.  I didn't test it yet, but maybe try this:
```javascript
sortTable.number = function(Cell) {
    var value = sortTable.stripTags(Cell.innerHTML).replace(/,/g, '')
    return /^((?:[-+]?\d+)?(?:\.\d+)?(?<=\d)(?:e[-+]?\d+)?|0x[0-9a-f]+)$/igm.test(value)
        ? Number(value)
        : Number(value.replace(/[^-\d.]/g, ''));
};
```
Let me know how this works for you.

**Comment by xjtu-blacksmith** [comment]
Fine! It works very well, thank you!
