### ISSUE TITLE
colNum is not increased when header has js-sort-none class

### ISSUE THREAD

**Issue by adamnowocin** [stationer/SortTable#6]
https://github.com/stationer/SortTable/blob/54ec5d229037ce1b56d0a1f2ad6f778e33aa00b4/sort-table.js#L266

colNum is not increased when header has js-sort-none class and when you later sort the table it gets value from wrong column

**Comment by tyleruebele** [comment]
Thank you.  That bug appears to have been added in https://github.com/stationer/SortTable/issues/5.

It should be easy to fix as https://github.com/stationer/SortTable/pull/7/files?diff=unified&w=1.

I didn't test this yet, so I didn't merge it yet, but it looks straightforward.

**Comment by tyleruebele** [comment]
merged
