### ISSUE TITLE
Date sort

### ISSUE THREAD

**Issue by teicors** [stationer/SortTable#8]
Hi, I'm having an issue during the sort of a date or may be is better to say "which format of data should I use in order to keep the right ordering?". I'm using the italian format but I'm having this sort from the earliest date:

29/08/2020
28/09/2020
28/07/2020
27/09/2020

Is it possible to specify the format ?

Thanks,
Angelo

**Comment by tyleruebele** [comment]
There is not currently a way to specify the format, but, there is an easy way to create a new sort time.
See the existing date helper function at https://github.com/stationer/SortTable/blob/master/sort-table.js#L133
You can replace this in your own code, or add a new type by defining it like this:
```javascript
sortTable.date_dmy = function(Cell) {
    // parse the date in dmy format and return a comparable value such as a unix timestamp
};
```
Should you happen to do this before me, a pull request is welcome.

**Comment by tyleruebele** [comment]
PS. By default I think it uses the local computer's locale settings, because it leans on JS built in date handling.

**Comment by tyleruebele** [comment]
A work around could be to include a sortable values, such as an ISO date, or a unix timestamp, in a hidden span at the start of the cell and use the `raw` type.

**Comment by gfxpronettm** [comment]
I have almost the same issue with this, in my case it looks like it makes the mistake with an extra digit...
Also uploaded a screenshot to show what I mean. 
Screenshot: [https://i.gyazo.com/f0bfa1c85f17ebb342982e1ff59a2c51.png](url)
