### ISSUE TITLE
Decimal values acting funny

### ISSUE THREAD

**Issue by Sandbird** [stationer/SortTable#9]
I am trying to sort some decimal values but it doesnt recognise them properly. For example the 85.17 should be up top.

![Image](https://i.imgur.com/K4nuMLU.jpg)

I tried to trick it adding the **int** value inside  tags in the front but that didnt work either.

**Comment by tyleruebele** [comment]
A quick test works correctly for me.  Are  you setting the column type in the header?
```html
<th class="js-sort-number">
```
If you are already doing that, can you send me the markup for the `<table>` for me to test with?

**Comment by Sandbird** [comment]
oh i had no idea you can do that. It's my fault really...i was using the min.js version. It works now :) thanks!

**Comment by tyleruebele** [comment]
Sounds like a bug in the README file. ;) I'll have to mention available sort types in the README.
